// Copyright 2026 Volker Theile
// SPDX-License-Identifier: Apache-2.0

// Package controller coordinates local disk discovery, real-time uevent processing,
// periodic SMART assessments, and Kubernetes PhysicalDisk lifecycle management.
//
// ============================================================================
// Architecture & Design Principles
// ============================================================================
//
// 1. Dual-Role Component (Reconciler + Runnable):
//    DiskMonitor simultaneously implements two core controller-runtime interfaces:
//    - Reconciler: Handles Kubernetes API events when a user modifies a PhysicalDisk
//      spec (such as tuning spec.smartmontools.smartctl.extraCmdArgs). Redundant
//      events generated by the daemon's own inventory loop are suppressed via
//      predicate filtering.
//    - Runnable: Runs continuously alongside the controller manager to operate the
//      local udev Netlink event listener, periodic hardware inventory scans,
//      and debounced collection workflows.
//
// 2. Direct Client vs. Manager Cache Separation:
//    - Scoped Watch Cache: The controller-runtime manager cache is strictly filtered
//      to the local node (PhysicalDisks matching node-disk-sentinel.org/node-name
//      and the local Node object). This eliminates cluster-wide watch fan-out across
//      nodes and keeps memory consumption minimal.
//    - Direct API Client (rawClient): DiskMonitor's own hardware discovery, inventory
//      synchronization, and label self-healing intentionally bypass the scoped cache.
//      A disk with a missing or stale node label would be invisible to a cache-backed
//      Get/List, triggering duplicate-create errors instead of self-healing. The direct
//      client guarantees visibility into the authoritative API server state.
//
// 3. Dual Debouncing & Storm Protection:
//    Hardware events occur in sudden bursts. DiskMonitor employs two independent,
//    in-memory debounce timers to collapse event flurries before reconciling:
//    - Uevent Hotplug Debounce (--event-debounce, default: 1s): Collapses the rapid
//      cascade of kernel partition scanning and udev helper rules when a drive is inserted.
//    - Kernel Error Debounce (--kmsg-debounce, default: 5s): Failing drives under active
//      load can emit hundreds of block-layer errors per second. DiskMonitor buffers
//      these in-memory (recordKernelError) and waits for kernel error recovery
//      (SCSI aborts, link resets) and firmware reallocation to settle before triggering
//      a consolidated SMART scan and Kubernetes API update.
//
// 4. Missing Device Handling & Metrics Cleanup:
//    When a hot-swap drive is detached, issuing further sysfs or smartctl commands
//    would block or fail with EIO. Removals (ActionRemove, ActionOffline) are handled
//    immediately without debouncing: the disk is flagged as missing
//    (ConditionDataCollected = False, Reason = DiskMissing) and all exported
//    hardware metrics are pruned (DeleteDeviceHealthMetrics) to alert operators
//    without delay and prevent stale gauge export.
package controller
